spring:
  application:
    name: spring-examples
  datasource:
    url: 'jdbc:mysql://114.116.213.241:3306/2018214247?serverTimezone=Asia/Shanghai'
    username: 2018214247
    password: 2018214247
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'