###

GET http://localhost:8080/api/user/1


###
GET http://localhost:8080/api/user/2


###
PATCH http://localhost:8080/api/users
Content-Type: application/json

{
  "id": "1",
  "name": "liu"
}


###
DELETE http://localhost:8080/api/users/1


###